name: Autograde C Assignment

on:
  push:
    paths:
      - '**.c'
      - 'test.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set permissions
      run: chmod +x test.sh

    - name: Run grading script
      run: ./test.sh
